#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'mongodb-10gen',
	:git =>  'https://github.com/higanworks-cookbooks/mongodb-10gen'

cookbook 'setup-mongo',
	:git => 'https://github.com/intere/setup-mongo.git'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
